/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Desktop;

import javax.swing.JOptionPane;

/**
 *
 * @author AP
 */
public class Home_pg extends javax.swing.JFrame {

    /**
     * Creates new form Home_pg
     */
    public Home_pg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        books_ch = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_dis = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        food_ch = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jToolBar2 = new javax.swing.JToolBar();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\dt_logo_7KL_icon (1)-0.jpg")); // NOI18N
        jLabel1.setLabelFor(this);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DEEP");
        jLabel2.setToolTipText("");
        jLabel2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel2InputMethodTextChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("THOUGHT");

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\download__3__Zsx_icon.jpg")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\1478663_KWT_icon.jpg")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\1b61acff7e34e1c660430d41b7cc54b9_q9v_icon.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 652, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\images.jpg")); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        books_ch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        books_ch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose to read", "Religious", "Science and Technology", "Fiction", "Entertainment and Sports", "Art and Craft", "Yoga And Music", "Tour and Travel", " " }));
        jPanel1.add(books_ch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 220, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Read");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 150, 40));

        text_dis.setEditable(false);
        text_dis.setColumns(20);
        text_dis.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        text_dis.setRows(5);
        jScrollPane1.setViewportView(text_dis);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 490, 350));

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\download.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 270, 170));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Books Suggestion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 120, -1));

        food_ch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        food_ch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select to Know", "AP|Andhra Pradesh", "AR|Arunachal Pradesh", "AS|Assam", "BR|Bihar", "CT|Chhattisgarh", "GA|Goa", "GJ|Gujarat", "HR|Haryana", "HP|Himachal Pradesh", "JK|Jammu and Kashmir", "JH|Jharkhand", "KA|Karnataka", "KL|Kerala", "MP|Madhya Pradesh", "MH|Maharashtra", "MN|Manipur", "ML|Meghalaya", "MZ|Mizoram", "NL|Nagaland", "OR|Odisha", "PB|Punjab", "RJ|Rajasthan", "SK|Sikkim", "TN|Tamil Nadu", "TG|Telangana", "TR|Tripura", "UT|Uttarakhand", "UP|Uttar Pradesh", "WB|West Bengal", "AN|Andaman and Nicobar Islands", "CH|Chandigarh", "DN|Dadra and Nagar Haveli", "DD|Daman and Diu", "DL|Delhi", "LD|Lakshadweep", "PY|Puducherry", " " }));
        jPanel1.add(food_ch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 220, 40));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("GET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 140, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Indian State and \nUnion Territories foods");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 260, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Result Here");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 136, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1060, 660));

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jToolBar2.setRollover(true);
        getContentPane().add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        label1.setText("label1");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2InputMethodTextChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        	String book = (String) books_ch.getSelectedItem();
                try
                {
                  if(book.isEmpty()||book=="Choose to read") 
                  {
                      JOptionPane.showMessageDialog(null, "Select any valid choice");
                  }
                  else if(book=="Art and Craft")
                  {
                   text_dis.setText("Most Popular Art and Craft Books For Kids\n" +
"1> The Ultimate Craft Book For Kids. Image courtesy Parragon Book Service. ..." +
"2> My First Craft Book, by Emma Hardy. ...\n" +
"3> I Am Never Bored, by author Serah Devos. ...\n" +
"4>How to Survive the School Holidays, by author Verity Davidson. ...\n" +
"5>Creative World Of Paper Folding, Origami Projects – Book 1.");
                  }
                }   
                catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String food = (String) food_ch.getSelectedItem();
        try
                {
                  if(food.isEmpty()||food=="Select to Know") 
                  {
                      JOptionPane.showMessageDialog(null, "Select any valid choice");
                  }
                  else if(food=="AP|Andhra Pradesh")
                  {
                       text_dis.setText("Panasa Puttu Koora (Andhra Jackfruit Curry) Panasa Puttu Koora, also called Jackfruit curry, is a popular jackfruit dish. ...\n" +
"Gutti Vankaya Kura (Eggplant Curry) ...\n" +
"Andhra Pepper Chicken. ...\n" +
"Hyderabadi Biryani. ...\n" +
"Shikampuri Kebab. ...\n" +
"Kodi Pulao (Andhra-style Chicken Pulao)");
                  }
                  else if(food=="AR|Arunachal Pradesh")
                  {
                      text_dis.setText("Pika Pila. A traditional food item of Arunachal Pradesh that you will find in every household and restaurant is the Pika Pila. ...\n" +
"Lukter. ...\n" +
"Pehak. ...\n" +
"Chura Sabzi. ...\n" +
"Wungwut Ngam. ...\n" +
"Pasa. ...\n" +
"Papuk. ...\n" +
"Koat Pitha.");
                  }
                  else if(food=="BR|Bihar")
                  {
                    text_dis.setText(
"Litti Chokha. The national dish of Bihar is Litti Chokha. ...\n" +
"Sattu. Sattu is the staple food of Bihar. ...\n" +
"Kadhi Badi. Kadhi is the most common dish in India and it is as diverse as cultures. ...\n" +
"Chana Ghugni. Chana Ghugni is the nutritious and lip-smacking mid-day snack option. ...\n" +
"Dal Pitha. ...\n" +
"Mutton Kebabs. ...\n" +
"Chicken Korma. ...\n" +
"Malpua.");
                  }
                }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_pg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> books_ch;
    private javax.swing.JComboBox<String> food_ch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private java.awt.Label label1;
    private javax.swing.JTextArea text_dis;
    // End of variables declaration//GEN-END:variables
}
